version: '3.4'
services:
  etl:
    build:
      context: ../
      dockerfile: spark/Dockerfile
    depends_on: 
      - spark-master
    volumes:
      - ../data:/opt/spark-data
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - INPUT_DATA_PATH=/opt/spark-data/
      - OUTPUT_DATA_PATH=/opt/spark-data/best_daily

  spark-master:
    image: bitnami/spark:3
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../data:/opt/spark-data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  
  spark-worker:
    image: bitnami/spark:3
    ports:
      - "8081:8081"
    volumes:
      - ../data:/opt/spark-data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
