version: '3.4'
services:
  etl:
    build:
      context: ../
      dockerfile: spark/Dockerfile
    volumes:
      - ../data:/opt/spark-data
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      INPUT_DATA_PATH: /opt/spark-data/
      OUTPUT_DATA_PATH: /best_daily
      AWS_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev_pass
      AWS_S3_BUCKET: example
    depends_on:
      minio-create-bucket:
        condition: service_completed_successfully

  spark-master:
    image: bitnami/spark:3
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../data:/opt/spark-data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  
  spark-worker:
    image: bitnami/spark:3
    ports:
      - "8081:8081"
    volumes:
      - ../data:/opt/spark-data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  minio:
    image: minio/minio:RELEASE.2021-10-27T16-29-42Z
    ports:
      - "9000:9000"
      - "8060:8060"
    environment:
      MINIO_ROOT_USER: root_user
      MINIO_ROOT_PASSWORD: root_user_password
      MINIO_ACCESS_KEY: dev
      MINIO_SECRET_KEY: dev_pass
    command: server /data --console-address ":8060"
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 0s
      retries: 5
      start_period: 2s

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root_user root_user_password;
      /usr/bin/mc admin info myminio;
      /usr/bin/mc mb myminio/example;
      /usr/bin/mc policy set download myminio/example;
      /usr/bin/mc admin user add myminio dev dev_pass;
      /usr/bin/mc admin policy set myminio readwrite user=dev;
      exit 0;
      "
